### ISSUE TITLE
Improvement: handling of enum types

### ISSUE THREAD

**Issue by johnnovak** [status-im/nim-toml-serialization#31]
It would be nice to have an option to encode/decode enum types with their displayable name instead of their ordinal value. The ordinal value is not useful at all for readability and manually changing the configs in most cases.

I think this is an important issue because one of the major selling points of TOML is readability/easy modifyability by humans.

Happy to give the implementation of this a go if you guys think it's a good idea.

**Comment by jangko** [comment]
Hi @johnnovak. Of course this is a good idea. 
I assume the `displayable name` is a `TOML-string` and not something like Nim identifier because TOML does not support YAML string.

The reader/decoder actually already able to parse both `ordinal` and `string` for an enum. But yes the encoder only write ordinal value for enum. This is intentional by design.

What if a user want to serialize his enum into a `TOML-string`? He could overload the enum writer like this:
```Nim
proc writeValue*(w: var TomlWriter, val: EnumA | EnumB | EnumC) =
   w.writeValue($val) 
   # or
   w.stream.writeText $val
```

I think we only need to update the documentation.

**Comment by johnnovak** [comment]
Cool, wasn't sure you can override writers like that. That's great! But then I have only read the readme and the tests.

Maybe updating the documentation and perhaps adding some tests/examples for the overriding would be a good idea then.

**Comment by johnnovak** [comment]
Btw, yeah, I was thinking of TOML strings, that's perfectly fine.

**Comment by jangko** [comment]
> Maybe updating the documentation and perhaps adding some tests/examples for the overriding would be a good idea then.

please go ahead.

**Comment by jangko** [comment]
one more thing, the override capability is actually part of [nim-serialization](https://github.com/status-im/nim-serialization) framework feature. but the documentation still have plenty of empty sections :)
