### ISSUE TITLE
Compile-time Support

### ISSUE THREAD

**Issue by Patitotective** [status-im/nim-toml-serialization#46]
Right now if you try to load (or decode) a TOML file at compile time (using the `{.compileTime}` pragma or `const`) you get an error.  
I am using TOML for a configuration file and it's important that I can read it at compile time. Not sure if this is possible or if there is a workaround.
Thanks
```nim
import toml_serialization

let data {.compileTime.} = Toml.loadFile("data.toml", TomlValueRef)
```
```
/home/me/.nimble/pkgs/faststreams-0.3.0/faststreams/inputs.nim(247, 26) Error: cannot evaluate at compile time: memFileInputVTable
```
Version `0.2.1`.

**Comment by jangko** [comment]
fast-streams can be modified to support compile time evaluation.
But nim-serialization currently cannot be modified to support compile time evaluation because it's already employs macros and templates heavily. And looks like Nim compiler reach it's limit when evaluating double tiers metaprogramming. It's become very hard to refactor templates running in Nim VM, and is equally hard to simplify the code to reproduce it if we want to report it to Nim dev team. hence toml-serialization cannot be used at compile time.

Have been there, and my statement is not just a speculation or assumption. Maybe we can revisit this issue in far future where Nim compiler have been improved to handle this situation.
